# This workflow will test a Java project with Maven

name: Build and Test Java Project with Maven

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build and Test with Maven
        run: mvn test
